# Generated by Django 3.2.5 on 2024-11-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_thread_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='topic',
            field=models.CharField(choices=[('1', 'Social life'), ('2', 'Professors'), ('3', 'Schedule'), ('4', 'Mental Health'), ('5', 'Programming'), ('6', 'Math'), ('7', 'Languages'), ('8', 'Other')], default=1, max_length=32),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
